"""empty message

Revision ID: 6a7c5fc41787
Revises: 1cbaee6cbaa6
Create Date: 2022-07-29 07:52:32.033955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a7c5fc41787'
down_revision = '1cbaee6cbaa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'courses', 'teachers', ['teacher_id'], ['id'])
    op.create_foreign_key(None, 'courses', 'assignments', ['assignment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.alter_column('courses', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
