"""empty message

Revision ID: 7c2787781147
Revises: eb52e2f54ee1
Create Date: 2022-07-29 19:22:15.501906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c2787781147'
down_revision = 'eb52e2f54ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'received_grade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('received_grade', sa.NUMERIC(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
