"""empty message

Revision ID: b1318a49df82
Revises: 6a7c5fc41787
Create Date: 2022-07-29 08:15:45.324713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1318a49df82'
down_revision = '6a7c5fc41787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('course_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'assignments', 'courses', ['course_id'], ['id'])
    op.drop_constraint('courses_assignment_id_fkey', 'courses', type_='foreignkey')
    op.drop_column('courses', 'assignment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('assignment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('courses_assignment_id_fkey', 'courses', 'assignments', ['assignment_id'], ['id'])
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_column('assignments', 'course_id')
    # ### end Alembic commands ###
