"""empty message

Revision ID: 111846611f5c
Revises: e0387f021502
Create Date: 2022-07-22 10:26:25.877480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111846611f5c'
down_revision = 'e0387f021502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('teachacct_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'teachers', ['teachacct_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='unique')
    op.drop_column('teachers', 'teachacct_id')
    # ### end Alembic commands ###
