"""empty message

Revision ID: e540df31cd02
Revises: 03aeaeb2f34e
Create Date: 2022-07-29 07:35:30.694608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e540df31cd02'
down_revision = '03aeaeb2f34e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(' grades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('received_grade', sa.Numeric(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(' grades')
    # ### end Alembic commands ###
