"""empty message

Revision ID: 13b1faa45693
Revises: e540df31cd02
Create Date: 2022-07-29 07:49:33.166054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13b1faa45693'
down_revision = 'e540df31cd02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(' grades')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(' grades',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'" grades_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('received_grade', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assignment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], name=' grades_assignment_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=' grades_student_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=' grades_pkey')
    )
    # ### end Alembic commands ###
